#!/usr/bin/env bash
# Script that does a bunch of things
echo $$ >> /var/run/myscript.pid

trap "echo 'I hate the kill command'; rm -rf /var/run/myscript.pid; pkill -f 100-process_and_pi_file" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -rf /var/run/holbertonscript.pid; pkill -f 100-process_and_pi_file" SIGQUIT

while true
do
    echo 'To infinity and beyond'
    sleep 2
done
