#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine it’s executed on
ifconfig | grep -oP "(?<=inet\s)((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])(\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])){3})"
